name:                egv
version:             0.1.0.0
github:              "wenkokke/egv"
license:             BSD3
author:              "Wen Kokke"
maintainer:          "wen.kokke@gmail.com"
copyright:           "Copyright (C) 2018 Wen Kokke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wenkokke/egv#readme>

dependencies:
- base         >= 4.7 && < 5
- containers
- size-based   >= 0.1 && < 0.2
- testing-feat >= 1   && < 2
- lazy-search  >= 0.1 && < 0.2

library:
  source-dirs: src

executables:
  egv-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egv

tests:
  egv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egv
