name:                egv
version:             0.1.0.0
github:              "wenkokke/egv"
license:             BSD3
author:              "Wen Kokke"
maintainer:          "wen.kokke@gmail.com"
copyright:           "Copyright (C) 2018 Wen Kokke"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/wenkokke/egv#readme>

dependencies:
- base           >= 4.7     && < 5
- containers     >= 0.6     && < 0.7
- size-based     >= 0.1.2.0 && < 0.2
- lazy-search    >= 0.1.2.1 && < 0.2
- testing-feat   >= 1.1.0.0 && < 2
- indexed        >= 0.1.3   && < 0.2
- indexed-extras >= 0.2     && < 0.3


library:
  source-dirs: src

executables:
  egv-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egv

tests:
  egv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egv
